# This chart assumes that ISTIO is deployed together with a load balancer - like MetalLB - that can provide a VIP to the istio ingress gateway

apiVersion: v2
name: idea4rc-capsule
description: Helm Chart for IDEA4RC Capsule deployment
dependencies:
  - name: etl
    version: 01.10.24-1600
    repository: file://./charts/etl
  - name: workbench
    version: "30.09.24-1200"
    repository: file://./charts/workbench
  - name: ohdsi-api
    version: "10.10.24-1156"
    repository: file://./charts/ohdsi-api
  - name: idea4rc-fhir-server
    repository: file://./charts/idea4rc-fhir-server
    version: 09.10.24-1754
    alias: fhirDataServer
  - name: idea4rc-fhir-server
    repository: file://./charts/idea4rc-fhir-server
    version: 09.10.24-1754
    alias: fhirDictionary

type: application
version: 10.10.24-1156
appVersion: "10.10.24-1156"
