# This chart assumes that ISTIO is deployed together with a load balancer 
# - like MetalLB - that can provide a VIP to the istio ingress gateway

apiVersion: v2
name: idea4rc-capsule
description: Helm Chart for IDEA4RC Capsule deployment

type: application
version: 01.08.24-1027
appVersion: "01.08.24-1027"
