# This chart assumes that ISTIO is deployed together with a load balancer 
# - like MetalLB - that can provide a VIP to the istio ingress gateway

apiVersion: v2
name: idea4rc-capsule
description: Helm Chart for IDEA4RC Capsule deployment
dependencies:
  - name: etl-fhir
    version: 23.09.24-1531
    repository: file://./charts/etl-fhir

type: application
version: 23.09.24-1531
appVersion: "23.09.24-1531"
