# This chart assumes that ISTIO is deployed together with a load balancer that can provide a VIP to the istio ingress gateway

apiVersion: v2
name: idea4rc-capsule
description: Helm Chart for IDEA4RC Capsule deployment

type: application
version: 23.11.6
appVersion: "0.2"