# This chart assumes that ISTIO is deployed together with a load balancer 
# - like MetalLB - that can provide a VIP to the istio ingress gateway

apiVersion: v2
name: idea4rc-capsule
description: Helm Chart for IDEA4RC Capsule deployment

type: application
version: 14.10.24-1125
appVersion: "14.10.24-1125"
