# This chart assumes that ISTIO is deployed together with a load balancer - like MetalLB - that can provide a VIP to the istio ingress gateway

apiVersion: v2
name: idea4rc-capsule
description: Helm Chart for IDEA4RC Capsule deployment
dependencies:
  - name: etl
    version: 16.06.25-1256
    repository: file://./charts/etl
  - name: workbench
    version: "30.09.24-1200"
    repository: file://./charts/workbench
  - name: idea4rc-fhir-server
    repository: file://./charts/idea4rc-fhir-server
    version: 15.10.24-1830
    alias: fhirDataServer
  - name: omop
    repository: file://./charts/omop
    version: 07.11.24-1542
  - name: feasibility-cohort-builder-exec
    repository: file://./charts/feasibility-cohort-builder-exec
    version: 17.10.2025-1740
    alias: fcbexec
  - name: nlp-ingestion
    repository: file://./charts/nlp-ingestion
    version: 23.07.25-1000
    alias: nlp
  - name: node
    repository: "@vantage6"
    version: "5.0.0-a40"
    alias: v6node

type: application
version: 27.10.2025-1123
appVersion: "27.10.2025-1123"
