#Rabbitmq Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.name }}
  namespace: {{ .Values.rabbitmq.namespace }}
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.name }}
    spec:
      containers:
      - name: {{ .Values.rabbitmq.name }}
        image: {{ .Values.rabbitmq.image }}
        ports:
        - containerPort: {{ .Values.rabbitmq.port.rabbitPort }}
        - containerPort: {{ .Values.rabbitmq.port.managementPort }}