{{- $PasswordValue := (randAlpha 16) | b64enc }}
{{- $secret := (lookup "v1" "Secret" .Values.fhirDictionary.server.namespace "fhir-dicionary-postgres-secret") }}
{{- if $secret }}
  {{- $PasswordValue = index $secret.data "POSTGRES_PASSWORD" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: fhir-dicionary-postgres-secret
  namespace: {{ .Values.fhirDictionary.server.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ "fhir" | b64enc }}
  POSTGRES_PASSWORD: {{ $PasswordValue }}