---
#Data Extraction Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dataextraction.service.name }}
  namespace: {{ .Values.dataextraction.namespace }}
spec:
  type: {{ .Values.dataextraction.service.type }}
  ports:
    - port: {{ .Values.dataextraction.service.port }}
      targetPort: {{ .Values.dataextraction.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.dataextraction.service.swaggerPort }}
      targetPort: {{ .Values.dataextraction.service.swaggerTargetPort }}
      protocol: TCP
      name: swagger
  selector:
    app: {{ .Values.dataextraction.name }}
