#This policy can be used to put mtls mode in PERMISSIVE for aerospike only
#to avoid networking issues between ETL and aerospike 
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "aerospike-istio-policy"
  namespace: {{ .Values.aerospike.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.aerospike.name }}
  mtls:
    mode: {{ .Values.aerospike.server.mtlsMode }}