apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ideadb.server.name }}
  namespace: {{ .Values.ideadb.namespace }}
  labels:
    app: {{ .Values.ideadb.server.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.ideadb.server.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ideadb.server.name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ideadb/ideadb-secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Values.ideadb.server.name }}
        image: "{{ .Values.ideadb.server.image }}"
        imagePullPolicy: {{ .Values.ideadb.server.imagePullPolicy | quote }}
        env:
        - name: MARIADB_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: ideadb-secret
              key: mariadbRootUser
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ideadb-secret
              key: mariadbRootPassword
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: ideadb-secret
              key: mariadbUser
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ideadb-secret
              key: mariadbPassword
        - name: MARIADB_DATABASE
          value: {{ .Values.ideadb.db.name }}
        ports:
        - name: mysql
          containerPort: {{ .Values.ideadb.db.port }}
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
#        resources:
#{{ toYaml .Values.resources | indent 10 }}
#        volumeMounts:
#        - name: data
#          mountPath: /mariadb
#      volumes:
#      - name: config
#        configMap:
#          name: {{ .Values.ideadb.server.name }}
#      - name: data
#      {{- if .Values.ideadb.server.persistence.enabled  }}
#        persistentVolumeClaim:
#          claimName: {{ .Values.ideadb.server.name }}
#      {{- else }}
#        emptyDir: {}
#      {{- end -}}