{{- $mariadbRootUser := (randAlpha 16) | b64enc }}
{{- $mariadbRootPassword := (randAlpha 16) | b64enc }}
{{- $mariadbUser := (randAlpha 16) | b64enc }}
{{- $mariadbPassword := (randAlpha 16) | b64enc }}
{{- $secret := (lookup "v1" "Secret" .Values.ideadb.namespace "ideadb-secret") }}
{{- if $secret }}
  {{- $mariadbRootUser = index $secret.data "mariadbRootUser" }}
  {{- $mariadbRootPassword = index $secret.data "mariadbRootPassword" }}
  {{- $mariadbUser = index $secret.data "mariadbUser" }}
  {{- $mariadbPassword = index $secret.data "mariadbPassword" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: ideadb-secret
  namespace: {{ .Values.ideadb.namespace }}
  labels:
    app: {{ .Values.ideadb.server.name }}
type: Opaque
data:
  mariadbRootUser: {{ $mariadbRootUser }}
  mariadbRootPassword: {{ $mariadbRootPassword }}
  mariadbUser: {{ $mariadbUser }}
  mariadbPassword: {{ $mariadbPassword }}
  #mariadbUser and mariadbPassword are used for the actual connection to the MARIADB_DATABASE