apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.revproxy.service.name }}
  namespace: {{ .Values.revproxy.namespace }}
spec:
  selector:
    app:  {{ .Values.revproxy.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.revproxy.service.port }}
      targetPort: {{ .Values.revproxy.service.target_port }}
  type: {{ .Values.revproxy.service.type }}