{{- $PasswordValue := (randAlpha 16) | b64enc }}
{{- $secret := (lookup "v1" "Secret" .Values.omop.namespace "omop-secret") }}
{{- if $secret }}
  {{- $PasswordValue = index $secret.data "POSTGRES_PASSWORD" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: omop-secret
  namespace: {{ .Values.omop.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ "omopadmin" | b64enc }}
  POSTGRES_PASSWORD: {{ $PasswordValue }}