{{- if .Values.omop.vocabJob -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.omop.vocab.name }}
  namespace: {{ .Values.omop.namespace }}
spec:
  ttlSecondsAfterFinished: {{ .Values.omop.vocab.ttl }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/omop/omop-secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: populate-omop-db
          image: {{ .Values.omop.vocab.image }}
          imagePullPolicy: {{ .Values.omop.vocab.pullPolicy }}
          env:
            - name: VOCAB_PG_HOST
              value: {{ .Values.omop.service.name }}.{{ .Values.omop.namespace }}.svc.cluster.local
            - name: VOCAB_PG_DATABASE
              value: {{ .Values.omop.db.name }}
            - name: VOCAB_PG_USER
              valueFrom:
                secretKeyRef:
                  name: omop-secret
                  key: POSTGRES_USER
            - name: VOCAB_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: omop-secret
                  key: POSTGRES_PASSWORD
            - name: VOCAB_PG_SCHEMA
              value: {{ .Values.omop.db.schema }}
      restartPolicy: OnFailure
{{- end }}