namespace: datamesh
server:
  name: ideadb
  image: bitnami/mariadb:11.4.2
  imagePullPolicy: IfNotPresent
  config: ""
  persistence:
    enabled: false
    storageClass: generic
    accessMode: ReadWriteOnce
    size: 8Gi
db:
  name: ideadb
  port: 3306
service:
  name: ideadb-svc
  port: 3306
  targetPort: mysql