## FHIR data server configuration
service:
  name: fhir-data-svc
  type: ClusterIP
  port: 8080
  targetPort: 8080
metrics:
  serviceMonitor:
    enabled: false
  additionalLabels: {}
  service:
    port: 8081
pod_disruption_budget:
  enabled: false
  minAvailable: 1
  maxUnavailable: ""
server:
  name: fhir-data-server
  namespace: datamesh
  replicas: 1
  image_pull_secrets: []
  pod_security_context: {}
  security_context:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    privileged: false
    seccompProfile:
      type: RuntimeDefault
  container_name: fhir-data-server
  image:
    registry: ghcr.io
    repository: idea4rc/fhir-data-server
    tag: "1.0"
    pull_policy: IfNotPresent
  startup_probe:
    httpGet:
      path: /readyz
      port: http
    failureThreshold: 10
    initialDelaySeconds: 30
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 30
  liveness_probe:
    httpGet:
      path: /livez
      port: http
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 30
  readiness_probe:
    httpGet:
      path: /readyz
      port: http
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 20
  customConfigPath: /app/config
  customConfigName: application-extra.yaml
  resources:
    {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  spring:
    spring_pgsql_driver: org.postgresql.Driver
    fhir_hibernateDialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
    #the following params are manually set in the corresponding template due to parsing issues with helm
    #use_apache_addr_strategy: "true"
    #probe_add_paths: "true"
    #mgmt_srv_port: "8081"
    extra_config: ""
    extra_env: ""
  node_selector: {}
  affinity: {}
  tolerations: []
  topology_spread_constraints: []
db:
  name: fhir-data-postgres-db
  replicas: 1
  image: postgres:13-alpine
  port: 5432
  dbName: idea4rc
  service:
    name: fhir-data-postgres-db
    port: 5432
    targetPort: 5432
    type: ClusterIP
idea4rcStorageClass:
  name: idea4rc-hostpath
virtualService:
  enabled: false