## ETL to FHIR
etl:
  namespace: datamesh
  server:
    name: eng-etl
    image: ghcr.io/idea4rc/etl:1.0
    port: 4001
    #proxy: "false"
    server_dns: "https://"
    hibernate_dialect: org.hibernate.dialect.PostgreSQLDialect
    spring_driver: org.postgresql.Driver
  db:
    name: etl
    replicas: 1
    image: postgres:16.3-bullseye
    port: 5432
    service:
      name: etl-postgres-db
      port: 5432
      target_port: 5432
      type: ClusterIP
  service:
    name: etl-svc
    type: ClusterIP
    port: 4001
    target_port: 4001
  storageclass:
    name: idea4rc-hostpath

## Aerospike
aerospike:
  name: aerospike
  namespace: datamesh
  server:
    keystore_namespace: idea4rc
    image: "aerospike/aerospike-server:7.1"
    port: 3000
    mtls_mode: PERMISSIVE
  service:
    name: aerospike-svc
    type: ClusterIP
    port: 3000
    target_port: 3000
aerospike:
  name: aerospike
  namespace: datamesh
  server:
    keystore_namespace: idea4rc
    image: "aerospike/aerospike-server:7.1"
    port: 3000
    mtls_mode: PERMISSIVE
  service:
    name: aerospike-svc
    type: ClusterIP
    port: 3000
    target_port: 3000