{{- $PasswordValue := (randAlpha 16) | b64enc }}
{{- $secret := (lookup "v1" "Secret" .Values.etl.namespace "etl-secret") }}
{{- if $secret }}
  {{- $PasswordValue = index $secret.data "ETL_PGSQL_PASSWORD" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: etl-secret
  namespace: {{ .Values.etl.namespace }}
type: Opaque
data:
  ETL_PGSQL_USER: {{ "etl" | b64enc }}
  ETL_PGSQL_PASSWORD: {{ $PasswordValue}}