{{- if .Values.virtualService.enabled -}}
# Dataextractor virtual service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dataextract-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - istio-ingressgateway
  http:
  - match:
    - uri:
        prefix: /dataextdocs/
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Values.service.name }}.{{ .Values.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.swaggerPort }}
  - match:
    - uri:
        prefix: /dataext/
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Values.service.name }}.{{ .Values.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
{{- end }}
