{{- $PasswordValue := (randAlpha 16) | b64enc }}
{{- $secret := (lookup "v1" "Secret" .Values.namespace "dataextract-secret") }}
{{- if $secret }}
  {{- $PasswordValue = index $secret.data "DATAEXTRACT_PGSQL_PASSWORD" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: dataextract-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DATAEXTRACT_PGSQL_USER: {{ "dataextractor" | b64enc }}
  DATAEXTRACT_PGSQL_PASSWORD: {{ $PasswordValue }}