#Data Extraction Jobs Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/dataextract-postgres-secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.server.image }}
          env:
            - name: CAPSULEFHIR_URL
              value: "{{ .Values.fhir.service.name }}.{{ .Values.fhir.namespace }}.svc.cluster.local:8080/baseR4"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: dataextract-secret
                  key: DATAEXTRACT_PGSQL_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dataextract-secret
                  key: DATAEXTRACT_PGSQL_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.db.dbName }}
            - name: POSTGRES_HOST
              value: "{{ .Values.db.service.name }}.{{ .Values.namespace }}.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "{{ .Values.db.port }}"
            - name: SWAGGER_URL
              value: "http://{{ .Values.capsulePublicHost }}/dataext/api/doc/swagger.json"
            - name: DROP_DB
              value: "{{ .Values.server.dropdb }}"
          ports:
            - containerPort: {{ .Values.server.port }}
            - containerPort: {{ .Values.server.swaggerPort }}
