---
#FHIR service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.server.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.metrics.service.port }}
      targetPort:  {{ .Values.metrics.service.port }}
      protocol: TCP
      name: http-metrics
  selector:
    app: {{ .Values.server.name }}
