{{- $PasswordValue := (randAlpha 16) | b64enc }}
{{- $secret := (lookup "v1" "Secret" .Values.server.namespace .Values.db.secret.name) }}
{{- if $secret }}
  {{- $PasswordValue = index $secret.data "POSTGRES_PASSWORD" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secret.name }}
  namespace: {{ .Values.server.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ "fhir" | b64enc }}
  POSTGRES_PASSWORD: {{ $PasswordValue }}