{{- if .Values.virtualService.enabled -}}
#FHIR virtual service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fhir-vs
  namespace: {{ .Values.server.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - istio-ingressgateway
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Values.service.name }}.{{ .Values.server.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
{{- end }}
