{{- if .Values.ohdsi.virtualService.enabled -}}
#OHDSI API virtual service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ohdsi-vs
  namespace: {{ .Values.ohdsi.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - istio-ingressgateway
  http:
  - match:
    - uri:
        prefix: /ohdsi-api/
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Values.ohdsi.service.name }}.{{ .Values.ohdsi.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.ohdsi.service.port }}
{{- end }}
