#OHDSI API deployment
#{{ $secret := ( lookup "v1" "Secret" .Values.celery.namespace "celery-secret" ) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ohdsi.name }}
  namespace: {{ .Values.ohdsi.namespace }}
  labels:
    app: {{ .Values.ohdsi.name }}
spec:
  replicas: {{ .Values.ohdsi.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.ohdsi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ohdsi.name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/celery/celery-secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Values.ohdsi.name }}
        image: {{ .Values.ohdsi.image }}
        imagePullPolicy: {{ .Values.ohdsi.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.ohdsi.port }}
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: celery-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: celery-secret
                key: POSTGRES_USER
          - name: POSTGRES_DB
            value: {{ .Values.celery.db.database }}
          - name: CELERY_BROKER_URL
            value: "amqp://guest:guest@{{ .Values.rabbitmq.service.name }}.{{ .Values.rabbitmq.namespace }}.svc.cluster.local:{{ .Values.rabbitmq.service.rabbitPort }}/"
          - name: CELERY_RESULT_BACKEND
            value: "db+postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ .Values.celery.db.service.name }}.{{ .Values.celery.namespace }}.svc.cluster.local:{{ .Values.celery.db.service.port}}/{{ .Values.celery.db.database }}"
          - name: OMOP_DBMS
            value: postgresql
          - name: OMOP_SERVER
            value: {{ .Values.omop.service.name }}.{{ .Values.omop.namespace }}.svc.cluster.local
          - name: OMOP_PORT
            value: "{{ .Values.omop.service.port }}"
          - name: OMOP_USER
            valueFrom:
              secretKeyRef:
                name: omop-secret
                key: POSTGRES_USER
          - name: OMOP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: omop-secret
                key: POSTGRES_PASSWORD
          - name: OMOP_DATABASE
            value: {{ .Values.omop.db.name }}
          - name: OMOP_CDM_SCHEMA
            value: {{ .Values.omop.db.schema }}
          - name: OMOP_RESULT_SCHEMA
            value: {{ .Values.omop.db.result_schema }}