apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.workbench.service.name }}
  namespace: {{ .Values.workbench.namespace }}
spec:
  selector:
    app:  {{ .Values.workbench.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.workbench.service.port }}
      targetPort: {{ .Values.workbench.service.target_port }} 
  type: {{ .Values.workbench.service.type }}