{{- $PasswordValue := (randAlpha 16) | b64enc }}
{{- $secret := (lookup "v1" "Secret" .Values.ohdsi.namespace "celery-secret") }}
{{- if $secret }}
  {{- $PasswordValue = index $secret.data "POSTGRES_PASSWORD" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: celery-secret
  namespace: {{ .Values.ohdsi.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ "celery" | b64enc }}
  POSTGRES_PASSWORD: {{ $PasswordValue }}  