{{- if .Values.server.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.server.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.server.name }}
  annotations:
    volume.alpha.kubernetes.io/storage-class: {{ .Values.server.storageClass | quote }}
spec:
  accessModes:
    - {{ .Values.server.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size | quote }}
{{- end }}