{{- $mariadbRootUser := (randAlpha 16) | b64enc }}
{{- $mariadbRootPassword := (randAlpha 16) | b64enc }}
{{- $mariadbUser := (randAlpha 16) | b64enc }}
{{- $mariadbPassword := (randAlpha 16) | b64enc }}
{{- $secret := (lookup "v1" "Secret" .Values.namespace "ideadb-secret") }}
{{- if $secret }}
  {{- $mariadbRootUser = index $secret.data "mariadb-root-user" }}
  {{- $mariadbRootPassword = index $secret.data "mariadb-root-password" }}
  {{- $mariadbUser = index $secret.data "mariadb-user" }}
  {{- $mariadbPassword = index $secret.data "mariadb-password" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: ideadb-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.server.name }}
type: Opaque
data:
  mariadb-root-user: {{ $mariadbRootUser }}
  mariadb-root-password: {{ $mariadbRootPassword }}
  mariadb-user: {{ $mariadbUser }}
  mariadb-password: {{ $mariadbPassword }}
  #mariadbUser and mariadbPassword are used for the actual connection to the MARIADB_DATABASE