apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.server.name }}-secret"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.server.name }}
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: {{ .Values.server.name }}