{{- $commonName := .Values.tls.commonName -}}
{{- $cert := genSelfSignedCert $commonName nil nil 3650 -}}
{{- $key := $cert.Key -}}
{{- $certPem := $cert.Cert -}}

apiVersion: v1
kind: Secret
metadata:
  name: "ingress-tls-secret"
  namespace: "istio-system"
type: kubernetes.io/tls
data:
  tls.crt: {{ $certPem | b64enc }}
  tls.key: {{ $key | b64enc }}