{{- $commonName := .Values.tls.commonName -}}
{{- $cert := genSelfSignedCert $commonName nil nil 3650 -}}
{{- $key := $cert.Key | b64enc -}}
{{- $certPem := $cert.Cert |b64enc -}}
{{- $secret := (lookup "v1" "Secret" "istio-system" "ingress-tls-secret") }}
{{- if $secret }}
  {{- $certPem = index $secret.data "tls.crt" }}
  {{- $key = index $secret.data "tls.key" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: "ingress-tls-secret"
  namespace: "istio-system"
type: kubernetes.io/tls
data:
  tls.crt: {{ $certPem }}
  tls.key: {{ $key }}