---
# NLP Results UI Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nlpingestion.resultsui.name }}
  namespace: {{ .Values.nlpingestion.resultsui.namespace }}
spec:
  replicas: {{ .Values.nlpingestion.resultsui.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nlpingestion.resultsui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nlpingestion.resultsui.name }}
    spec:
      containers:
        - name: {{ .Values.nlpingestion.resultsui.name }}
          image: {{ .Values.nlpingestion.resultsui.image }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: BASE_URL_PATH 
              value: {{ .Values.nlpingestion.resultsui.baseURL | quote }}
          volumeMounts:
            - mountPath: /data/results
              name: resultsui-pv
            - mountPath: /var/cache/nginx
              name: nginx-cache
      volumes:
        - name: resultsui-pv
          persistentVolumeClaim:
            claimName: resultsui-pv-claim
        - name: nginx-cache
          emptyDir: {}
