---
#Capsule virtual service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fhir-server
  namespace: {{ .Values.fhir.server.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.istio_gateway_name }}
  http:
  - match:
    - uri:
        prefix: /dataextraction
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Values.dataextraction.service.name }}.{{ .Values.dataextraction.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.dataextraction.service.port }}
  - match:
    - uri:
        prefix: /etl
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Values.etl.service.name }}.{{ .Values.etl.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.etl.service.port }}
  - match:
    - uri:
        prefix: /
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Values.fhir.service.name }}.{{ .Values.fhir.server.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.fhir.service.port }}
