#Capsule virtual service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fhir-server
  namespace: {{ .Values.fhir.server.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.istio_gateway_name }}
  http:
  - match:
    - uri:
        prefix: /ohdsi-api/
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Values.ohdsi.service.name }}.{{ .Values.ohdsi.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.ohdsi.service.port }}
  - match:
    - uri:
        prefix: /dataextdocs/
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Values.dataextraction.service.name }}.{{ .Values.dataextraction.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.dataextraction.service.swagger_port }}
  - match:
    - uri:
        prefix: /dataext/
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Values.dataextraction.service.name }}.{{ .Values.dataextraction.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.dataextraction.service.port }}
  - match:
    - uri:
        prefix: /etl/
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Values.etl.service.name }}.{{ .Values.etl.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.etl.service.port }}
  - match:
    - uri:
        prefix: /workbench/
    rewrite:
        uri: "/workbench/"
    route:
    - destination:
        host: {{ .Values.revproxy.service.name }}.{{ .Values.workbench.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.workbench.service.port }}
  - match:
    - uri:
        prefix: /
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Values.fhir.service.name }}.{{ .Values.fhir.server.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.fhir.service.port }}
