#Celery Secrets
apiVersion: v1
kind: Secret
metadata:
  name: celery-secrets
  namespace: {{ .Values.ohdsi.namespace }}
type: Opaque
data:
  POSTGRES_USER: "b2hkc2l1c2VyCg=="
  POSTGRES_PASSWORD: "ZGppb2FzamRvaXpueGN2Cg=="
  