---
#ETL virtual service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.etl.server.name }}
  namespace: {{ .Values.etl.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.istio_gateway_name }}
  http:
  - match:
    - uri:
        prefix: /etl
    rewrite:
        uri: "/"
    route:
    - destination:
        host: {{ .Values.etl.server.name }}.{{ .Values.etl.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.etl.service.port }}