---
#FHIR deployment
# add custom application to
# target: /app/config/application.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fhir.server.name }}
  namespace: {{ .Values.fhir.server.namespace }}
spec:
  replicas: {{ .Values.fhir.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.fhir.server.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.fhir.server.name }}
      {{- with .Values.fhir.server.pod_annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.fhir.server.image_pull_secrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.fhir.server.pod_security_context | nindent 8 }}
      containers:
        - name: {{ .Values.fhir.server.container_name }}
          securityContext:
            {{- toYaml .Values.fhir.server.security_context | nindent 12 }}
          image: {{ .Values.fhir.server.image.registry }}/{{ .Values.fhir.server.image.repository }}:{{ .Values.fhir.server.image.tag }}
          imagePullPolicy: {{ .Values.fhir.server.image.pull_policy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: http-metrics
              containerPort: 8081
              protocol: TCP
          {{- with .Values.fhir.server.startup_probe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.liveness_probe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readiness_probe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.fhir.server.resources | nindent 12 }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.fhir.server.spring.spring_data_source_url }}
            - name: SPRING_DATASOURCE_USERNAME
              {{- toYaml .Values.fhir.server.spring.spring_data_source_username | nindent 14 }}
            - name: SPRING_DATASOURCE_PASSWORD
              {{- toYaml .Values.fhir.server.spring.spring_data_source_password | nindent 14 }}
            - name: SPRING_DATASOURCE_DRIVERCLASSNAME
              value: {{ .Values.fhir.server.spring.spring_pgsql_driver }}
            - name: spring.jpa.properties.hibernate.dialect
              value: {{ .Values.fhir.server.spring.fhir_hibernate_dialect }}
            - name: HAPI_FHIR_USE_APACHE_ADDRESS_STRATEGY
              #value: {{ .Values.fhir.server.spring.use_apache_addr_strategy }}
              value: "true"
            - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ADD_ADDITIONAL_PATHS
              #value: {{ .Values.fhir.server.spring.probe_add_paths }}
              value: "true"
            - name: MANAGEMENT_SERVER_PORT
              #value: {{ .Values.fhir.server.spring.mgmt_srv_port }}
              value: "8081"
            {{- if .Values.fhir.server.spring.extra_config }}
            - name: SPRING_CONFIG_IMPORT
              {{- toYaml .Values.fhir.server.spring.extra_config | nindent 14 }}
            {{- end }}
            {{- if .Values.fhir.server.extra_env }}
            {{ toYaml .Values.fhir.server.extra_env | nindent 12 }}
            {{- end }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
            - mountPath: /app/target
              name: lucenefiles-volume
          {{- if .Values.extraConfig }}
            - name: application-extra-config
              mountPath: /app/config/application-extra.yaml
              readOnly: true
              subPath: application-extra.yaml
          {{- end }}
      {{- with .Values.fhir.server.node_selector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fhir.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fhir.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fhir.server.topology_spread_constraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: lucenefiles-volume
          emptyDir: {}