---
#FHIR virtual service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fhir-server
  namespace: {{ .Values.fhir.server.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.istio_gateway_name }}
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
        uri: "/"
    route:
    - destination:
        host: fhir-service.datamesh.svc.cluster.local
        port:
          number: {{ .Values.fhir.service.port }}