apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ideadb.server.name }}
  namespace: {{ .Values.ideadb.namespace }}
  labels:
    app: {{ .Values.ideadb.server.name }}

data:
  my.cnf: |-
{{- if .Values.ideadb.server.config }}
{{ .Values.ideadb.server.config | indent 4 }}
{{- end -}}