apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ideadb.server.name }}
  namespace: {{ .Values.ideadb.namespace }}
  labels:
    app: {{ .Values.ideadb.server.name }}
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: {{ .Values.ideadb.server.name }}