apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ohdsi.service.name }}
  namespace: {{ .Values.ohdsi.namespace }}
spec:
  selector:
    app: {{ .Values.ohdsi.service.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.ohdsi.service.port }}
      targetPort: {{ .Values.ohdsi.port }}
  type: {{ .Values.ohdsi.service.type }}