apiVersion: v1
kind: ConfigMap
metadata:
  name: connection-details
data:
  OMOP_DBMS: "postgresql"
  OMOP_SERVER: "host.docker.internal"
  OMOP_PORT: {{ .Values.omop.cdm.port }}
  OMOP_USER: {{ .Values.omop.db.user }}
  #OMOP_PASSWORD: "mysecretpassword"
  OMOP_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: omop-secrets
        key: POSTGRES_PASSWORD
  OMOP_DATABASE: {{ .Values.omop.db.name }}
  OMOP_SCHEMA: {{ .Values.omop.db.schema }}
  CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672/"
  #CELERY_RESULT_BACKEND: "db+postgresql://postgres:mysecretpassword@db/omopdb"
  CELERY_RESULT_BACKEND: "db+postgresql://$OMOP_USER:$OMOP_PASSWORD@db/$OMOP_DATABASE"