apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.omop.vocab.name }}
  namespace: {{ .Values.omop.namespace }}
spec:
  ttlSecondsAfterFinished: {{ .Values.omop.vocab.ttl }}
  template:
    spec:
      containers:
        - name: populate-omop-db
          image: {{ .Values.omop.vocab.image }}
          imagePullPolicy: {{ .Values.omop.vocab.pullpolicy }}
          env:
            - name: VOCAB_PG_HOST
              value: {{ .Values.omop.service.name }}
            - name: VOCAB_PG_DATABASE
              value: {{ .Values.omop.db.name }}
            - name: VOCAB_PG_USER
              value: {{ .Values.omop.db.user }}
            - name: VOCAB_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: omop-secrets
                  key: POSTGRES_PASSWORD
            - name: VOCAB_PG_SCHEMA
              value: {{ .Values.omop.db.schema }}
      restartPolicy: OnFailure