apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.fhir.server.namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres_user }}
  POSTGRES_PASSWORD: {{ .Values.postgres_password }}