apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: {{ .Values.fhir.server.namespace }}
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432 
      targetPort: 5432
  type: ClusterIP
  # type: ExternalName
  # externalName: my.database.example.com