apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: {{ .Values.fhir.server.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          #volumeMounts:
          #- mountPath: /var/lib/postgresql/data
          #  name: postgres-pv-claim
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: idea4rc
      #volumeMounts:
      #  - mountPath: /var/lib/postgresql/data
      #    name: postgres-pv-claim