#Rabbitmq Service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.service.name }}
  namespace: {{ .Values.rabbitmq.namespace }}
spec:
  selector:
    app: {{ .Values.rabbitmq.name }}
  ports:
    - name : rabbitmq-port
      protocol: TCP
      port:  {{ .Values.rabbitmq.service.rabbit_port }}
      targetPort:  {{ .Values.rabbitmq.port.rabbit_port }}
    - name : management-port
      protocol: TCP
      port: {{ .Values.rabbitmq.service.management_port }}
      targetPort: {{ .Values.rabbitmq.port.management_port }}