#Data Extraction Jobs Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.workbench.name }}
  namespace: {{ .Values.workbench.namespace }}
spec:
  replicas: {{ .Values.workbench.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.workbench.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.workbench.name }}
    spec:
      containers:
        - name: {{ .Values.workbench.name }}
          image: {{ .Values.workbench.image }}
          env:
            - name: BACK_END_BASE_PATH
              value: "http://{{ .Values.etl.service.name }}.{{ .Values.etl.service.namespace }}.svc.cluster.local:{{ .Values.etl.service.port }}/"
          ports:
            - containerPort: {{ .Values.workbench.port }}