{{- if .Values.authEnable -}}

apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "jwt-fhir"
  namespace: {{ .Values.fhir.server.namespace }}
spec:
  selector:
    matchLabels:
      app: fhir-server
  jwtRules:
  - issuer: {{ .Values.jwt_issuer }}
    jwksUri: {{ .Values.jwtsUri }}

{{- end }}