apiVersion: batch/v1
kind: Job
metadata:
  name: create-capsule-node-secret
  namespace: {{ .Values.defaultNamespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: secret-manager
      restartPolicy: OnFailure
      containers:
        - name: secret-creator
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              set -e

              echo "Fetching omop-secret..."
              SECRET=$(kubectl get secret omop-secret -n {{ .Values.omop.namespace }} -o json)
              USER=$(echo "$SECRET" | jq -r '.data.POSTGRES_USER' | base64 -d)
              PASSWORD=$(echo "$SECRET" | jq -r '.data.POSTGRES_PASSWORD' | base64 -d)

              echo "Creating capsule-node secret..."
              kubectl create secret generic idea4rc-capsule-node-secrets \
                --namespace {{ .Values.defaultNamespace }} \
                --from-literal=DATABASE_OMOP_USER="$USER" \
                --from-literal=DATABASE_OMOP_PASSWORD="$PASSWORD" \
                --from-literal=DATABASE_OMOP_TYPE={{ "other" | b64enc }} \
                --from-literal=DATABASE_OMOP_URI={{ "jdbc:postgres://{{ .Values.omop.service.name }}.{{ .Values.omop.namespace}}.svc.cluster.local:{{ .Values.omop.service.port }}/{{ .Values.omop.db.name }}" | b64enc }} \
                --from-literal=V6_API_KEY="{{ .Values.v6node.node.apiKey | b64enc}}" \
                --from-literal=V6_NODE_NAME="{{ .Values.v6node.node.name | b64enc }}" \
                --from-literal=KEYCLOAK_CLIENT={{ .Values.v6node.node.keycloak.client | b64enc }} \
                --from-literal=KEYCLOAK_CLIENT_SECRET="{{ .Values.v6node.node.keycloak.clientSecret | b64enc }}" \
                --dry-run=client -o yaml | kubectl apply -f -
