apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager
  namespace: {{ .Values.defaultNamespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
  namespace: {{ .Values.defaultNamespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager
  namespace: {{ .Values.defaultNamespace }}
subjects:
  - kind: ServiceAccount
    name: secret-manager
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
