#FHIR DB persistent Volume Claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fhir-pg-pv-claim
  namespace: {{ .Values.fhir.server.namespace }}
spec:
  storageClassName: {{ .Values.idea4rcStorageClass.name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
