#Celery DB deployment
#{{ $secret := ( lookup "v1" "Secret" .Values.celery.namespace "celery-secret" ) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.celery.db.name }}
  namespace: {{ .Values.celery.namespace }}
spec:
  replicas: {{ .Values.celery.db.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.celery.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.celery.db.name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/celery-db/celery-secret.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/omop/omop-secret.yaml") . | sha256sum }}
    spec:
      volumes:
      - persistentVolumeClaim: 
          claimName: celery-pv-claim
        name: celery-pv
      containers:
      - name: {{ .Values.celery.db.name }}
        image: {{ .Values.celery.db.image }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: celery-pv
        ports:
          - containerPort:  {{ .Values.celery.db.port }}
        env:
          - name: POSTGRES_INITDB_ARGS
            value: -A md5
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: celery-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: celery-secret
                key: POSTGRES_USER
          - name: POSTGRES_DB
            value: {{ .Values.celery.db.database }}
          - name: CELERY_BROKER_URL
            value: "amqp://guest:guest@{{ .Values.rabbitmq.service.name }}.{{ .Values.rabbitmq.namespace }}.svc.cluster.local:{{ .Values.rabbitmq.service.rabbit_port }}/"
          - name: CELERY_RESULT_BACKEND
            value: "db+postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ .Values.celery.db.service.name }}.{{ .Values.celery.namespace }}.svc.cluster.local:{{ .Values.celery.db.service.port}}/{{ .Values.celery.db.database }}"
          - name: OMOP_DBMS
            value: postgresql
          - name: OMOP_SERVER
            value: {{ .Values.omop.service.name }}.{{ .Values.omop.namespace }}.svc.cluster.local
          - name: OMOP_PORT
            value: "{{ .Values.omop.service.port }}"
          - name: OMOP_USER
            valueFrom:
              secretKeyRef:
                name: omop-secret
                key: POSTGRES_USER
          - name: OMOP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: omop-secret
                key: POSTGRES_PASSWORD
          - name: OMOP_DATABASE
            value: {{ .Values.omop.db.name }}
          - name: OMOP_CDM_SCHEMA
            value: {{ .Values.omop.db.schema }}